### ISSUE TITLE
editing event in /pk package results in an error (internal onSave event)

### ISSUE THREAD

**Issue by larsgson** [unfoldingWord/oce-editor-tools#47]
The onSave event works fine for both the /core and /simple packages
- it results in an error, however, in the /pk package
- the call stack for the error exception includes Highlited.jsx from /src/findr/highlights/components, so there is a suspicion that the error might be related to the highlighting code
- the error message is:
`TypeError: Cannot read properties of undefined (reading 'outerHTML')`

In order to reproduce the error:
- go to https://oce-editor-tools-pk.netlify.app/
- click inside an Editor pane in the PkEditor Workspace
- make a change
- move the cursor to a different paragraph
_(note: there is a more detailed error stack, if this is done while debugging locally)_

**Comment by larsgson** [comment]
Update:
- I temporarily created a version of oce-editor-tools/core where I disabled the use of Highlighted, but this did not resolve the problem. So my suspicion that something was not right in Highlighted seems to be wrong.
- and I have now discovered that the problem only appears in the left editor pane in the PkEdit styleguidist example. The right side (Titus in French) works fine.

So I am now going to look into this some more, why it is sometimes working, sometimes not...

**Comment by larsgson** [comment]
While trying to narrow down the error, I have now found a strange behaviour:
The second editor pane works fine (regardless of content), but the first editor pane always breaks

**Comment by elsylambert** [comment]
@larsgson Is this change implemented in gatewayTranslate?

**Comment by larsgson** [comment]
@elsylambert yes, this is now fixed - and also included in gT v1.0
